from sqlalchemy import Column, Integer, Float, String, DateTime, ForeignKey, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db.database import Base


class UserPattern(Base):
    """
    Stores learned patterns per user per task type.
    Updated by the ML system (Person 1) after enough data is collected.
    Example: "You underestimate research tasks by 40%"
    """
    __tablename__ = "user_patterns"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    task_type = Column(String, nullable=False)          # matches TaskType enum values

    # Accuracy tracking
    avg_accuracy = Column(Float, nullable=True)         # 0.0 to 1.0 (1.0 = perfect)
    systematic_bias = Column(Float, nullable=True)      # + means underestimates, - means overestimates
    calibration_factor = Column(Float, default=1.0)     # Multiplier applied to raw predictions

    # Stats
    total_tasks_completed = Column(Integer, default=0)
    avg_actual_time = Column(Float, nullable=True)      # Average actual minutes for this task type
    avg_estimated_time = Column(Float, nullable=True)   # Average estimate for this task type

    # Human-readable insight generated by AI
    insight_text = Column(Text, nullable=True)          # e.g. "You underestimate research by 40%"

    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    user = relationship("User", back_populates="patterns")

    def __repr__(self):
        return f"<UserPattern user_id={self.user_id} task_type={self.task_type} bias={self.systematic_bias}>"