"""Sync user capacity and alert fields

Revision ID: dd4597cf6e82
Revises: a1b2c3d4e5f6
Create Date: 2026-03-07 01:18:34.023946

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd4597cf6e82'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration — runs on `alembic upgrade head`"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtasks', 'completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration — runs on `alembic downgrade -1`"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtasks', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
